# Generated by Django 4.1.7 on 2023-02-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_catogry_alter_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='catogry',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='courses.category'),
        ),
    ]
